### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by d1qqn** [244v234/ESP8266-WifiPhisher#4]
i got this error:

> sketch\Alert.cpp: In member function 'bool Alert::alertOptions(String, String, String, String)':
> Alert.cpp:45:15: error: 'class SSD1306Wire' has no member named 'drawFillRoundRect'
>        display.drawFillRoundRect(display.getWidth() / 4 - widthBtn / 2, topBtn,
>                ^
> Alert.cpp:52:15: error: 'class SSD1306Wire' has no member named 'drawRoundRect'
>        display.drawRoundRect(display.getWidth() / 4 + display.getWidth() / 2 -
>                ^
> Alert.cpp:69:15: error: 'class SSD1306Wire' has no member named 'drawRoundRect'
>        display.drawRoundRect(display.getWidth() / 4 - widthBtn / 2, topBtn,
>                ^
> Alert.cpp:72:15: error: 'class SSD1306Wire' has no member named 'drawFillRoundRect'
>        display.drawFillRoundRect(display.getWidth() / 4 +
>                ^
> sketch\Alert.cpp: In member function 'bool Alert::alertNotify(String, String, String)':
> Alert.cpp:113:13: error: 'class SSD1306Wire' has no member named 'drawFillRoundRect'
>      display.drawFillRoundRect(display.getWidth() / 2 - widthBtn / 2, topBtn,
>              ^
> sketch\Attack.cpp: In member function 'void Attack::start()':
> Attack.cpp:23:16: error: 'D4' was not declared in this scope
>    digitalWrite(D4, LOW);
>                 ^
> sketch\Attack.cpp: In member function 'void Attack::stop()':
> Attack.cpp:55:18: error: 'D4' was not declared in this scope
>      digitalWrite(D4, HIGH);
>                   ^
> sketch\Attack.cpp: In member function 'void Attack::deauthAllUpdate()':
> Attack.cpp:227:22: error: 'D4' was not declared in this scope
>          digitalWrite(D4, LOW);
>                       ^
> exit status 1
> 'class SSD1306Wire' has no member named 'drawFillRoundRect'

what can i do?

**Comment by d1qqn** [comment]
problem solved by replace the library files/folder: `ArduinoJson, SimpleButton, SSD1306, Time`
from: `\packages\deauther\hardware\esp8266\2.7.2\libraries`
with the library files from this repo.

**Comment by 244v234** [comment]
> problem solved by replace the library files/folder: `ArduinoJson, SimpleButton, SSD1306, Time`
> from: `\packages\deauther\hardware\esp8266\2.7.2\libraries`
> with the library files from this repo.

That's why I uploaded the entire library, instead of mentioning their names
